### PR TITLE
Refactor shared primitive typed data

### PR DESCRIPTION
**Pull request by pjcuadra**

### CODE REVIEW

**Comment by pjcuadra** [comment]
This pull request was only tested in simulator mode

**Comment by app4mc-rover** [comment]
Please try to refrain from changing any dependencies (opencv modules, raspicam) while adding features.
You are working on a deprecated version, so you forgot to make changes in all of the files (including imgproc task).
When you invent a new feature, it is advised that you describe it within the Pull Request!
I'll hold these changes until the migration period as more and more new features are added now.

**Comment by pjcuadra** [comment]
This is none new features. This is actually a fix + rework. I'm not working on a deprecated version, I'm using latest master. I'll revert the chages related to raspicam module since I introduced them accidentally.

**Comment by pjcuadra** [comment]
Done! The raspicam and opencv dependencies changes were reverted.

**Comment by pjcuadra** [comment]
BTW, the find raspicam module isn't really working just when it's installed in `/usr/local`. This isn't always the case, as in our AGL based image. That's why I'm not able to compile with raspicam and the image processing thread.

**Comment by pjcuadra** [comment]
Please don't hold this pull request that long. If more and more features are added then this change will be useless by then and we'll need to reimplement all this code.

**Pull request merged**
